# Generated by Django 3.2.6 on 2021-08-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Task', '0002_auto_20210812_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
